version: "3.7"
services:
  vasco-bank-autenticacao-api:
    container_name: vasco-bank-autenticacao-api
    image: vasco-bank-autenticacao-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      API_PORT: ${API_PORT}
      KID: ${KID}
      SERVICE_USUARIO: ${SERVICE_USUARIO}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: on-failure:5
    networks:
      - kong-net 

networks:
  kong-net:
    name: kong-net
    driver: bridge
