@baseUrl = {{$dotenv baseUrl}}
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

@uemail = jorge@email.com
@usenha = senha123

### AUTENTICAR
POST {{baseUrl}}/autenticacao/autenticar
Content-Type: {{contentType}}

{
    "email": "{{uemail}}",
    "senha": "{{usenha}}"
}


### VALIDAR
POST {{baseUrl}}/autenticacao/validar
Content-Type: {{contentType}}

{
    "tipo": "Bearer",
    "token": "eyJraWQiOiJWQUxVRSIsImFsZyI6IkhTNTEyIn0.eyJzdWIiOiJqb3JnZUBlbWFpbC5jb20iLCJleHAiOjE2ODg0NjI0MDl9.P5OeNZdAyRleTTgC_2IjaP1It3pGFhLuJ9hqzJNOdT9MNWYtIQq7CEgaXxnghAc75KkErJrnPPvHTIzypxR93w"
}

### INFORMACOES USUARIO LOGADO
GET {{baseUrl}}/autenticacao/quemsoueu
Authorization: Bearer eyJraWQiOiJWQUxVRSIsImFsZyI6IkhTNTEyIn0.eyJzdWIiOiJqb3JnZUBlbWFpbC5jb20iLCJleHAiOjE2ODg0NjI0MDl9.P5OeNZdAyRleTTgC_2IjaP1It3pGFhLuJ9hqzJNOdT9MNWYtIQq7CEgaXxnghAc75KkErJrnPPvHTIzypxR93w
