@baseUrl = {{$dotenv baseUrl}}
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

@uid = 1
@unome = usuario2
@uemail = usuario2@email.com
@usenha = 123

### REGISTRAR 
POST {{baseUrl}}/registrar
Content-Type: {{contentType}}

{
    "nome": "{{unome}}",
    "email": "{{uemail}}",
    "senha": "{{usenha}}"
}

### AUTENTICAR
POST {{baseUrl}}/autenticar
Content-Type: {{contentType}}

{
    "email": "{{uemail}}",
    "senha": "{{usenha}}"
}


### VALIDAR
POST {{baseUrl}}/validar
Content-Type: {{contentType}}

{
    "tipo": "Bearer",
    "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c3VhcmlvMkBlbWFpbC5jb20iLCJleHAiOjE2ODc5OTU5MTN9.hcUxUlPqHymJ5o-FivtWraenand8Xmg-4jFnR9TQ0nqO0RW_AYabGpNyiBw3Gqgfd4xGGqGlGQWiroE8XThE5g"
}

### INFORMACOES USUARIO LOGADO
GET {{baseUrl}}/usuario
Authorization: {{token}}
