@baseUrl = {{$dotenv baseUrl}}
@contentType = {{$dotenv contentType}}
@token = Bearer {{$dotenv token}}

@uid = 1
@unome = usuario
@uemail = usuario@email.com
@usenha = 123

### TODOS OS USUARIOS
GET {{baseUrl}}/usuarios
Authorization: {{token}}

### BUSCAR PELO ID
GET {{baseUrl}}/usuario/{{uid}}
Authorization: {{token}}
